In [2]:
import yfinance as yf
import pandas as pd
import numpy as np
import datetime as dt
from pandas.tseries.offsets import MonthEnd

In [3]:
wiki = "https://en.wikipedia.org/wiki/"

In [6]:
tickersSensex = pd.read_html(wiki+"BSE_SENSEX")[1].Symbol.to_list()

In [7]:
tickersSensex

['ASIANPAINT.BO',
 'AXISBANK.BO',
 'BAJAJ-AUTO.BO',
 'BAJFINANCE.BO',
 'BAJAJFINSV.BO',
 'BHARTIARTL.BO',
 'DRREDDY.BO',
 'HCLTECH.BO',
 'HDFC.BO',
 'HDFCBANK.BO',
 'HINDUNILVR.BO',
 'ICICIBANK.BO',
 'INDUSINDBK.BO',
 'INFY.BO',
 'ITC.BO',
 'KOTAKBANK.BO',
 'LT.BO',
 'M&M.BO',
 'MARUTI.BO',
 'NESTLEIND.BO',
 'NTPC.BO',
 'ONGC.BO',
 'POWERGRID.BO',
 'RELIANCE.BO',
 'SBIN.BO',
 'SUNPHARMA.BO',
 'TCS.BO',
 'TECHM.BO',
 'TITAN.BO',
 'ULTRACEMCO.BO']

In [9]:
len(tickersSensex)

30

In [10]:
df2 = yf.download(tickersSensex,start="2009-12-31",end="2022-12-31")

[*********************100%***********************]  30 of 30 completed

In [11]:
df2

               Adj Close                                          \
           ASIANPAINT.BO AXISBANK.BO BAJAJ-AUTO.BO BAJAJFINSV.BO
Date
2009-12-31    161.450546  180.494568    626.595276    338.869568
2010-01-04    160.857330  181.288696    616.174011    352.653961
2010-01-05    160.924728  184.383041    617.632263    353.046387
2010-01-06    160.025940  181.699463    609.291687    344.020355
2010-01-07    159.675385  183.096008    598.799194    341.861969
...                  ...         ...           ...           ...
2022-12-26   3057.500000  928.750000   3553.500000   1534.949951
2022-12-27   3109.800049  932.549988   3589.350098   1537.699951
2022-12-28   3124.000000  924.950012   3579.000000   1524.449951
2022-12-29   3115.300049  935.000000   3570.949951   1514.900024
2022-12-30   3091.800049  933.849976   3615.899902   1548.449951

                                                                               \
           BAJFINANCE.BO BHARTIARTL.BO   DRREDDY.BO   HCLTECH.BO      HDFC.BO
Date
2009-12-31     29.545971    284.969147  1034.020386    72.141014   447.408722
2010-01-04     30.607903    281.675751  1034.155762    72.063293   446.548218
2010-01-05     30.442116    286.095917  1064.259766    73.811691   448.035431
2010-01-06     30.581022    283.452515  1088.939575    71.393097   449.538971
2010-01-07     30.845379    285.272552  1071.537109    70.033195   441.978729
...                  ...           ...          ...          ...          ...
2022-12-26   6423.700195    811.200012  4247.549805  1021.993225  2660.699951
2022-12-27   6504.200195    814.750000  4248.649902  1027.146484  2667.300049
2022-12-28   6487.600098    803.450012  4253.250000  1026.056396  2670.899902
2022-12-29   6508.100098    819.450012  4259.100098  1035.124268  2675.199951
2022-12-30   6574.149902    806.700012  4234.399902  1029.673584  2636.649902

                         ...   Volume                                    \
            HDFCBANK.BO  ...  NTPC.BO  ONGC.BO POWERGRID.BO RELIANCE.BO
Date                     ...
2009-12-31   155.267761  ...  2205968   421698       851700     1444854
2010-01-04   155.710663  ...  1205161   263652       866894    28198842
2010-01-05   155.829361  ...  1446850   787938       774715     1583518
2010-01-06   156.094193  ...  1713954   962244      1007791     2153556
2010-01-07   156.404648  ...  1588611   594312       671743     2979154
...                 ...  ...      ...      ...          ...         ...
2022-12-26  1628.150024  ...   502229   431166       586251       95382
2022-12-27  1630.650024  ...   582715   485192      1850289      184837
2022-12-28  1629.449951  ...  2504811   331918       555042      168925
2022-12-29  1640.900024  ...  1010084   970441       587929      157229
2022-12-30  1627.300049  ...   128115  1232764       123423       77470


            SBIN.BO SUNPHARMA.BO  TCS.BO TECHM.BO TITAN.BO ULTRACEMCO.BO
Date
2009-12-31  6742310        95680  227184   116020   343520         19813
2010-01-04  3292160        99480  205618   282320   183260         58088
2010-01-05  3164620       148210  361778   408852   433380         85463
2010-01-06  4354310       177430  568174   218992   398900         41570
2010-01-07  2545580       122270  843042   198752   897740         20917
...             ...          ...     ...      ...      ...           ...
2022-12-26   368995       195524   18484    73861    39911         13642
2022-12-27   343276        24052   34548   100192    37904         33088
2022-12-28   258405        77782   41409    52333   102885         21593
2022-12-29   621617       117142   52967    21494    36181         19021
2022-12-30   544009        33728  182089   130312    23577         12485

[3210 rows x 180 columns]

In [12]:
prices = df2['Adj Close']
prices

,ASIANPAINT.BO,AXISBANK.BO,BAJAJ-AUTO.BO,BAJAJFINSV.BO,BAJFINANCE.BO,BHARTIARTL.BO,DRREDDY.BO,HCLTECH.BO,HDFC.BO,HDFCBANK.BO,...,NTPC.BO,ONGC.BO,POWERGRID.BO,RELIANCE.BO,SBIN.BO,SUNPHARMA.BO,TCS.BO,TECHM.BO,TITAN.BO,ULTRACEMCO.BO
Date,,,,,,,,,,,,,,,,,,,,,
2009-12-31,161.450546,180.494568,626.595276,338.869568,29.545971,284.969147,1034.020386,72.141014,447.408722,155.267761,...,117.172646,113.747482,78.811722,494.090027,197.634018,139.126633,289.054993,197.165161,65.990898,868.669861
2010-01-04,160.857330,181.288696,616.174011,352.653961,30.607903,281.675751,1034.155762,72.063293,446.548218,155.710663,...,115.233849,114.689339,80.422318,487.717804,199.562927,139.218918,289.806641,203.733368,65.930588,915.610901
2010-01-05,160.924728,184.383041,617.632263,353.046387,30.442116,286.095917,1064.259766,73.811691,448.035431,155.829361,...,113.990982,116.688881,80.565468,485.087311,199.589050,143.433105,289.498322,206.310898,67.313461,935.403015
2010-01-06,160.025940,181.699463,609.291687,344.020355,30.581022,283.452515,1088.939575,71.393097,449.538971,156.094193,...,113.518768,117.973618,81.173927,493.818085,200.734222,144.813156,282.905670,207.136871,68.410942,935.355591
2010-01-07,159.675385,183.096008,598.799194,341.861969,30.845379,285.272552,1071.537109,70.033195,441.978729,156.404648,...,113.419342,118.133018,81.961334,501.256012,199.650009,142.348358,275.522583,202.638626,70.062996,928.236023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-26,3057.500000,928.750000,3553.500000,1534.949951,6423.700195,811.200012,4247.549805,1021.993225,2660.699951,1628.150024,...,161.328049,141.300003,211.750000,2524.500000,596.750000,998.750000,3191.200195,1001.400024,2481.750000,7074.350098
2022-12-27,3109.800049,932.549988,3589.350098,1537.699951,6504.200195,814.750000,4248.649902,1027.146484,2667.300049,1630.650024,...,160.840805,144.899994,212.550003,2545.050049,601.849976,1000.299988,3194.336426,1010.099976,2503.649902,7106.450195
2022-12-28,3124.000000,924.950012,3579.000000,1524.449951,6487.600098,803.450012,4253.250000,1026.056396,2670.899902,1629.449951,...,161.474228,143.899994,215.649994,2544.449951,601.200012,995.049988,3191.641113,1016.099976,2581.199951,7047.250000
2022-12-29,3115.300049,935.000000,3570.949951,1514.900024,6508.100098,819.450012,4259.100098,1035.124268,2675.199951,1640.900024,...,162.399994,144.899994,215.800003,2542.550049,612.299988,1000.049988,3204.333984,1013.599976,2552.699951,6986.600098
2022-12-30,3091.800049,933.849976,3615.899902,1548.449951,6574.149902,806.700012,4234.399902,1029.673584,2636.649902,1627.300049,...,162.107651,146.800003,213.850006,2548.199951,613.200012,1000.700012,3194.532471,1016.500000,2597.949951,6959.049805

In [13]:
prices.index = pd.to_datetime(prices.index)

In [14]:
mtl_ret = prices.pct_change().resample('M').agg(lambda x: (x+1).prod() - 1)

In [15]:
mtl_ret

,ASIANPAINT.BO,AXISBANK.BO,BAJAJ-AUTO.BO,BAJAJFINSV.BO,BAJFINANCE.BO,BHARTIARTL.BO,DRREDDY.BO,HCLTECH.BO,HDFC.BO,HDFCBANK.BO,...,NTPC.BO,ONGC.BO,POWERGRID.BO,RELIANCE.BO,SBIN.BO,SUNPHARMA.BO,TCS.BO,TECHM.BO,TITAN.BO,ULTRACEMCO.BO
Date,,,,,,,,,,,,,,,,,,,,,
2009-12-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2010-01-31,0.031677,0.037221,0.006471,-0.068327,-0.061571,-0.067822,-0.016218,-0.064344,-0.110331,-0.040902,...,-0.091006,-0.066027,0.026967,-0.039333,-0.093172,-0.024982,-0.016471,-0.020341,0.053972,0.015627
2010-02-28,-0.023528,0.096880,0.024985,0.075668,-0.028927,-0.088907,0.015508,0.060615,0.049362,0.045252,...,-0.052509,0.015685,-0.049689,-0.065501,-0.034965,0.048623,0.034741,-0.079345,0.166900,0.116957
2010-03-31,0.128789,0.039339,0.106581,-0.033800,0.060077,0.116920,0.117354,-0.026262,0.085140,0.133664,...,0.034920,-0.016606,0.000467,0.098824,0.052205,0.161399,0.026019,-0.044714,0.052574,0.113862
2010-04-30,0.015838,0.084766,0.041371,0.028704,0.343328,-0.043283,-0.011435,0.104719,0.040198,0.030582,...,-0.000241,-0.039508,0.023798,-0.039222,0.105315,-0.124497,-0.018955,-0.093615,0.156744,-0.159085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,0.017780,0.036355,0.043875,0.128158,0.013164,0.076456,0.037711,-0.009908,0.028204,0.036077,...,0.091840,0.057408,0.083441,0.055126,0.005585,-0.050198,-0.027024,0.026504,0.106096,0.025191
2022-09-30,-0.014580,-0.023497,-0.136594,-0.901065,0.004621,0.100826,0.021050,-0.007239,-0.064059,-0.042928,...,-0.025023,-0.084446,-0.076002,-0.099049,-0.000188,0.062413,-0.064454,-0.063620,0.001479,-0.063342
2022-10-31,-0.069077,0.234969,0.040302,0.005451,-0.026964,0.040325,0.022485,0.128111,0.078729,0.052025,...,0.083568,0.056366,0.075183,0.072276,0.080501,0.070548,0.065472,0.054850,0.056205,0.074162
2022-11-30,0.024302,-0.004802,0.022089,-0.036113,-0.058350,0.020012,0.012310,0.075989,0.089827,0.075080,...,-0.004911,0.106046,0.005513,0.071718,0.050017,0.027954,0.062432,0.030584,-0.037449,0.054131
2022-12-31,-0.028439,0.035885,-0.035837,-0.048162,-0.022155,-0.049431,-0.056075,-0.072942,-0.020415,0.011531,...,-0.034252,0.040028,-0.045312,-0.067413,0.017759,-0.041796,-0.039250,-0.056437,-0.019623,-0.016632

In [16]:
past_11 = (mtl_ret+1).rolling(11).apply(np.prod)-1

In [17]:
past_11.head(11)

,ASIANPAINT.BO,AXISBANK.BO,BAJAJ-AUTO.BO,BAJAJFINSV.BO,BAJFINANCE.BO,BHARTIARTL.BO,DRREDDY.BO,HCLTECH.BO,HDFC.BO,HDFCBANK.BO,...,NTPC.BO,ONGC.BO,POWERGRID.BO,RELIANCE.BO,SBIN.BO,SUNPHARMA.BO,TCS.BO,TECHM.BO,TITAN.BO,ULTRACEMCO.BO
Date,,,,,,,,,,,,,,,,,,,,,
2009-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-10-31,0.507647,0.498332,0.747589,0.356861,1.400895,-0.006341,0.460968,0.100942,0.299012,0.348341,...,-0.15717,0.119163,-0.080095,0.012667,0.408019,0.409282,0.42819,-0.26148,1.514018,0.205285

In [18]:
formation = dt.datetime(2010,12,31)
formation

datetime.datetime(2010, 12, 31, 0, 0)

In [19]:
end_measurement = formation - MonthEnd(1)

In [20]:
end_measurement

Timestamp('2010-11-30 00:00:00')

In [22]:
ret_12 = past_11.loc[end_measurement]
ret_12

ASIANPAINT.BO    0.487522
AXISBANK.BO      0.397449
BAJAJ-AUTO.BO    0.818645
BAJAJFINSV.BO    0.363666
BAJFINANCE.BO    1.180204
BHARTIARTL.BO    0.099523
DRREDDY.BO       0.573140
HCLTECH.BO       0.099853
HDFC.BO          0.301469
HDFCBANK.BO      0.354911
HINDUNILVR.BO    0.155766
ICICIBANK.BO     0.325214
INDUSINDBK.BO    1.069960
INFY.BO          0.189291
ITC.BO           0.389749
KOTAKBANK.BO     0.186864
LT.BO            0.169216
M&M.BO           0.419738
MARUTI.BO       -0.082709
NESTLEIND.BO     0.447476
NTPC.BO         -0.203430
ONGC.BO          0.071889
POWERGRID.BO    -0.128269
RELIANCE.BO     -0.088064
SBIN.BO          0.337824
SUNPHARMA.BO     0.500534
TCS.BO           0.464786
TECHM.BO        -0.350575
TITAN.BO         1.616745
ULTRACEMCO.BO    0.238110
Name: 2010-11-30 00:00:00, dtype: float64

In [23]:
ret_12 = ret_12.reset_index()
ret_12

            index  2010-11-30 00:00:00
0   ASIANPAINT.BO             0.487522
1     AXISBANK.BO             0.397449
2   BAJAJ-AUTO.BO             0.818645
3   BAJAJFINSV.BO             0.363666
4   BAJFINANCE.BO             1.180204
5   BHARTIARTL.BO             0.099523
6      DRREDDY.BO             0.573140
7      HCLTECH.BO             0.099853
8         HDFC.BO             0.301469
9     HDFCBANK.BO             0.354911
10  HINDUNILVR.BO             0.155766
11   ICICIBANK.BO             0.325214
12  INDUSINDBK.BO             1.069960
13        INFY.BO             0.189291
14         ITC.BO             0.389749
15   KOTAKBANK.BO             0.186864
16          LT.BO             0.169216
17         M&M.BO             0.419738
18      MARUTI.BO            -0.082709
19   NESTLEIND.BO             0.447476
20        NTPC.BO            -0.203430
21        ONGC.BO             0.071889
22   POWERGRID.BO            -0.128269
23    RELIANCE.BO            -0.088064
24        SBIN.BO             0.337824
25   SUNPHARMA.BO             0.500534
26         TCS.BO             0.464786
27       TECHM.BO            -0.350575
28       TITAN.BO             1.616745
29  ULTRACEMCO.BO             0.238110

In [24]:
ret_12['decile'] = pd.qcut(ret_12.iloc[:,1],10,labels=False,duplicates='drop')
ret_12

            index  2010-11-30 00:00:00  decile
0   ASIANPAINT.BO             0.487522       7
1     AXISBANK.BO             0.397449       6
2   BAJAJ-AUTO.BO             0.818645       8
3   BAJAJFINSV.BO             0.363666       5
4   BAJFINANCE.BO             1.180204       9
5   BHARTIARTL.BO             0.099523       2
6      DRREDDY.BO             0.573140       8
7      HCLTECH.BO             0.099853       2
8         HDFC.BO             0.301469       4
9     HDFCBANK.BO             0.354911       5
10  HINDUNILVR.BO             0.155766       2
11   ICICIBANK.BO             0.325214       4
12  INDUSINDBK.BO             1.069960       9
13        INFY.BO             0.189291       3
14         ITC.BO             0.389749       6
15   KOTAKBANK.BO             0.186864       3
16          LT.BO             0.169216       3
17         M&M.BO             0.419738       6
18      MARUTI.BO            -0.082709       1
19   NESTLEIND.BO             0.447476       7
20        NTPC.BO            -0.203430       0
21        ONGC.BO             0.071889       1
22   POWERGRID.BO            -0.128269       0
23    RELIANCE.BO            -0.088064       1
24        SBIN.BO             0.337824       5
25   SUNPHARMA.BO             0.500534       8
26         TCS.BO             0.464786       7
27       TECHM.BO            -0.350575       0
28       TITAN.BO             1.616745       9
29  ULTRACEMCO.BO             0.238110       4

In [25]:
winners = ret_12[ret_12.decile == 9]
losers = ret_12[ret_12.decile == 0]

In [26]:
winnerret = mtl_ret.loc[formation + MonthEnd(1),mtl_ret.columns.isin(winners['index'])]
loserret = mtl_ret.loc[formation + MonthEnd(1),mtl_ret.columns.isin(losers['index'])]

In [27]:
Momentumprofit = winnerret.mean() - loserret.mean()
Momentumprofit

-0.056593460958753505

In [28]:
def momentum(formation):
    end_measurement = formation - MonthEnd(1)
    ret_12 = past_11.loc[end_measurement]
    ret_12 = ret_12.reset_index()
    ret_12['decile'] = pd.qcut(ret_12.iloc[:,1],10,labels=False,duplicates='drop')
    winners = ret_12[ret_12.decile == 9]
    losers = ret_12[ret_12.decile == 0]
    winnerret = mtl_ret.loc[formation + MonthEnd(1),mtl_ret.columns.isin(winners['index'])]
    loserret = mtl_ret.loc[formation + MonthEnd(1),mtl_ret.columns.isin(losers['index'])]
    Momentumprofit = winnerret.mean() - loserret.mean()
    return Momentumprofit

In [29]:
formation

datetime.datetime(2010, 12, 31, 0, 0)

In [30]:
momentum(formation)

-0.056593460958753505

In [32]:
for i in range(12*10):
    print(formation + MonthEnd(i))

2010-12-31 00:00:00
2011-01-31 00:00:00
2011-02-28 00:00:00
2011-03-31 00:00:00
2011-04-30 00:00:00
2011-05-31 00:00:00
2011-06-30 00:00:00
2011-07-31 00:00:00
2011-08-31 00:00:00
2011-09-30 00:00:00
2011-10-31 00:00:00
2011-11-30 00:00:00
2011-12-31 00:00:00
2012-01-31 00:00:00
2012-02-29 00:00:00
2012-03-31 00:00:00
2012-04-30 00:00:00
2012-05-31 00:00:00
2012-06-30 00:00:00
2012-07-31 00:00:00
2012-08-31 00:00:00
2012-09-30 00:00:00
2012-10-31 00:00:00
2012-11-30 00:00:00
2012-12-31 00:00:00
2013-01-31 00:00:00
2013-02-28 00:00:00
2013-03-31 00:00:00
2013-04-30 00:00:00
2013-05-31 00:00:00
2013-06-30 00:00:00
2013-07-31 00:00:00
2013-08-31 00:00:00
2013-09-30 00:00:00
2013-10-31 00:00:00
2013-11-30 00:00:00
2013-12-31 00:00:00
2014-01-31 00:00:00
2014-02-28 00:00:00
2014-03-31 00:00:00
2014-04-30 00:00:00
2014-05-31 00:00:00
2014-06-30 00:00:00
2014-07-31 00:00:00
2014-08-31 00:00:00
2014-09-30 00:00:00
2014-10-31 00:00:00
2014-11-30 00:00:00
2014-12-31 00:00:00
2015-01-31 00:00:00
2015-02-28 00:00:00
2015-03-31 00:00:00
2015-04-30 00:00:00
2015-05-31 00:00:00
2015-06-30 00:00:00
2015-07-31 00:00:00
2015-08-31 00:00:00
2015-09-30 00:00:00
2015-10-31 00:00:00
2015-11-30 00:00:00
2015-12-31 00:00:00
2016-01-31 00:00:00
2016-02-29 00:00:00
2016-03-31 00:00:00
2016-04-30 00:00:00
2016-05-31 00:00:00
2016-06-30 00:00:00
2016-07-31 00:00:00
2016-08-31 00:00:00
2016-09-30 00:00:00
2016-10-31 00:00:00
2016-11-30 00:00:00
2016-12-31 00:00:00
2017-01-31 00:00:00
2017-02-28 00:00:00
2017-03-31 00:00:00
2017-04-30 00:00:00
2017-05-31 00:00:00
2017-06-30 00:00:00
2017-07-31 00:00:00
2017-08-31 00:00:00
2017-09-30 00:00:00
2017-10-31 00:00:00
2017-11-30 00:00:00
2017-12-31 00:00:00
2018-01-31 00:00:00
2018-02-28 00:00:00
2018-03-31 00:00:00
2018-04-30 00:00:00
2018-05-31 00:00:00
2018-06-30 00:00:00
2018-07-31 00:00:00
2018-08-31 00:00:00
2018-09-30 00:00:00
2018-10-31 00:00:00
2018-11-30 00:00:00
2018-12-31 00:00:00
2019-01-31 00:00:00
2019-02-28 00:00:00
2019-03-31 00:00:00
2019-04-30 00:00:00
2019-05-31 00:00:00
2019-06-30 00:00:00
2019-07-31 00:00:00
2019-08-31 00:00:00
2019-09-30 00:00:00
2019-10-31 00:00:00
2019-11-30 00:00:00
2019-12-31 00:00:00
2020-01-31 00:00:00
2020-02-29 00:00:00
2020-03-31 00:00:00
2020-04-30 00:00:00
2020-05-31 00:00:00
2020-06-30 00:00:00
2020-07-31 00:00:00
2020-08-31 00:00:00
2020-09-30 00:00:00
2020-10-31 00:00:00
2020-11-30 00:00:00

In [33]:
profits = []
dates = []

for i in range(12*10):
    profits.append(momentum(formation + MonthEnd(i)))
    dates.append(formation + MonthEnd(i))

In [34]:
profits

[-0.056593460958753505,
 0.0029829430694129355,
 0.07432185297572998,
 0.04296571636942263,
 0.02876630003719275,
 -0.050960560247819475,
 0.03706173060029705,
 -0.04070911709738971,
 -0.02874894353182933,
 -0.040814168646782445,
 0.014034670318713721,
 0.09348157994317227,
 -0.3161280436744798,
 -0.005864718872343709,
 0.11023260266195375,
 0.04073504590678072,
 0.03900274022523779,
 -0.06720826858222737,
 0.08438871357051973,
 0.1537209285899191,
 0.019765059128360837,
 0.054259773243265655,
 -0.09410601197508375,
 0.05463385375378371,
 -0.10327162338839362,
 -0.009975104685753614,
 0.03420188508273651,
 -0.1305010525950172,
 0.06606421673213987,
 -0.06288279797792277,
 0.06339828405780712,
 0.05315810158955725,
 -0.00824905039847501,
 -0.08865396730747613,
 -0.1209269192926409,
 0.08937475389549217,
 0.1407018267625061,
 -0.00602590191457808,
 -0.24573563661636433,
 0.01008744627436823,
 -0.24058349242210722,
 0.0690939523244094,
 -0.03853710902280734,
 -0.005781736749997227,
 -0.01460923918841924,
 0.04419885862894979,
 0.07950232757280251,
 0.08182401300931981,
 0.1346011660533074,
 -0.051079216121636094,
 0.054103902548022,
 -0.0014783816020296954,
 -0.00944174765214334,
 0.08745466834317117,
 0.12037927350161634,
 0.005912715921464626,
 0.027774364802662675,
 -0.00723567109098662,
 0.009879742509604402,
 0.08126135369914236,
 0.06476128970870855,
 0.03003190127189377,
 -0.09189324927559313,
 0.005894531216764162,
 0.03516861723745057,
 0.060200941466058186,
 0.05556687302390725,
 0.012203322748022341,
 0.004086572872491738,
 0.0222059775590383,
 -0.12439115603432364,
 -0.09604609859867023,
 0.14805793271151566,
 -0.013528674552702943,
 0.05499004867960544,
 0.15380146136202089,
 0.08444251728298069,
 0.001300562660223048,
 0.2118567155278613,
 0.059289828913314024,
 -0.11007061914173814,
 -0.04593204124046624,
 0.10600351209722321,
 -0.03994611612222032,
 -0.03095139443358626,
 -0.018424690626995997,
 0.11118538081890125,
 0.03419466606277403,
 0.04136664730746238,
 -0.043538104081597084,
 0.06288954532711122,
 -0.03774696352963899,
 0.0717194687028218,
 0.00911917677118116,
 -0.07184332332613741,
 0.0027294887142802118,
 0.08081968000412498,
 -0.05085742474225245,
 0.0673952022509765,
 0.07839368224121002,
 0.030748669449986624,
 0.03687569236510472,
 -0.018766430586073996,
 -0.030127421827613854,
 0.11994474737670875,
 -0.059182650360945534,
 0.05322016066231975,
 0.054367598874817305,
 0.06422842188439604,
 0.1825924004646298,
 0.0020738424023011293,
 -0.08367079064201635,
 -0.024708971077623338,
 -0.11142183405522703,
 -0.043246970406724906,
 -0.2089289702163748,
 0.1923247548255957,
 -0.06227983292075001,
 -0.31028266753106687,
 0.0045902546543930695]